# Generated by Django 4.2 on 2024-07-31 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alumnos_profesores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='curso',
            new_name='nombre',
        ),
    ]
