# Generated by Django 4.2 on 2024-07-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_curso_curso_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='email',
        ),
    ]
